// 홈 각 섹션에 들어갈 콘텐츠(하드코딩을 화면에 흩뿌리지 않고 여기서 관리).
import type { MainAction } from "./home-logic";
import type { PlatformT } from "../i18n";

// 다음 행동별 예상 소요시간(있으면 배지로 노출).
export const actionTime: Record<MainAction["kind"], string | null> = {
  new: "약 5분",
  resume: "약 3분",
  applying: null,
  next: null
};

// 오늘의 취업 준비 팁 — 진행도에 따라 다른 팁을 보여준다(결정적).
export function homeTips(t: PlatformT): { title: string; desc: string }[] {
  return [
    { title: t("경험이 없다고 생각하지 마세요", "Don't think you have no experience", "别以为自己没有经验", "Đừng nghĩ bạn không có kinh nghiệm", "経験がないと思わないでください", "Jangan merasa tidak punya pengalaman"), desc: t("아르바이트·동아리·과제도 정리하면 훌륭한 취업 재료예요.", "Part-time jobs, clubs, and assignments all make great material for your job search.", "兼职、社团、作业整理好都是很好的求职素材。", "Việc làm thêm, câu lạc bộ, bài tập đều là chất liệu tuyệt vời cho việc xin việc.", "アルバイト・サークル・課題も整理すれば立派な就活の材料です。", "Kerja paruh waktu, klub, dan tugas pun jadi materi bagus untuk melamar kerja.") },
    { title: t("경험은 '결과'까지 적어야 강해져요", "Experience gets stronger when you add the 'result'", "写上『结果』，经验才更有力", "Kinh nghiệm mạnh hơn khi ghi cả 'kết quả'", "経験は『結果』まで書くと強くなります", "Pengalaman jadi kuat bila ditambah 'hasil'"), desc: t("무엇을 했는지에서 멈추지 말고, 그래서 어떤 변화가 생겼는지까지.", "Don't stop at what you did—add what changed because of it.", "别只停留在做了什么，还要写出因此带来了什么改变。", "Đừng dừng ở việc bạn đã làm gì, hãy ghi cả thay đổi mà nó tạo ra.", "何をしたかで止めず、それでどんな変化が生まれたかまで。", "Jangan berhenti di apa yang dilakukan—tambahkan perubahan yang dihasilkan.") },
    { title: t("성과에는 숫자를 넣어보세요", "Add numbers to your achievements", "在成果里加上数字", "Hãy thêm con số vào thành tích", "成果には数字を入れてみましょう", "Tambahkan angka pada pencapaian"), desc: t("'주문 누락 30% 감소'처럼 숫자가 있으면 훨씬 설득력 있어요.", "Numbers like 'cut order errors by 30%' make it far more convincing.", "像『订单遗漏减少30%』这样有数字会更有说服力。", "Con số như 'giảm 30% đơn bị sót' sẽ thuyết phục hơn nhiều.", "『注文漏れ30%削減』のように数字があると説得力が増します。", "Angka seperti 'kesalahan pesanan turun 30%' jauh lebih meyakinkan.") },
    { title: t("이력서는 직무에 맞춰 다듬어요", "Tailor your resume to the job", "简历要贴合职位来打磨", "Điều chỉnh CV cho phù hợp với vị trí", "履歴書は職務に合わせて整えます", "Sesuaikan resume dengan posisi"), desc: t("같은 경험도 지원 직무에 따라 강조점이 달라져요.", "The same experience can be emphasized differently depending on the role.", "同样的经验，会因应聘职位不同而侧重点不同。", "Cùng một kinh nghiệm nhưng điểm nhấn thay đổi tùy theo vị trí ứng tuyển.", "同じ経験でも応募職種によって強調点が変わります。", "Pengalaman yang sama bisa ditekankan berbeda tergantung posisinya.") },
    { title: t("자기소개서는 질문에 답하듯 써요", "Write your cover letter like answering questions", "自我介绍就像回答问题一样写", "Viết thư xin việc như đang trả lời câu hỏi", "自己PRは質問に答えるように書きます", "Tulis surat lamaran seperti menjawab pertanyaan"), desc: t("빈 화면부터 채우지 말고, 문항에 하나씩 답해보세요.", "Don't start from a blank page—answer each prompt one by one.", "别从空白页开始，一道题一道题地回答吧。", "Đừng bắt đầu từ trang trắng, hãy trả lời từng câu hỏi một.", "空白の画面から埋めず、設問に一つずつ答えてみましょう。", "Jangan mulai dari halaman kosong—jawab tiap pertanyaan satu per satu.") },
    { title: t("면접 답변은 경험으로 준비해요", "Prepare interview answers with your experiences", "用经验来准备面试回答", "Chuẩn bị câu trả lời phỏng vấn bằng kinh nghiệm", "面接の回答は経験で準備します", "Siapkan jawaban wawancara dengan pengalaman"), desc: t("예상 질문에 내 경험을 예시로 미리 정리해두면 편해요.", "Line up your experiences as examples for likely questions ahead of time.", "提前把自己的经验作为例子整理到预想问题上会更轻松。", "Chuẩn bị sẵn kinh nghiệm làm ví dụ cho các câu hỏi dự kiến sẽ nhẹ nhàng hơn.", "想定質問に自分の経験を例として先に整理しておくと楽です。", "Menyiapkan pengalaman sebagai contoh untuk pertanyaan yang mungkin muncul akan memudahkan.") }
  ];
}

export function pickTip(t: PlatformT, progress: number) {
  const tips = homeTips(t);
  const idx = Math.min(tips.length - 1, Math.floor((progress / 100) * tips.length));
  return tips[idx] ?? tips[0];
}

// 오늘의 한마디 — 지표가 아닌 따뜻한 응원 한 줄(날짜로 순환).
export const dailyMessages: string[] = [
  "오늘도 한 걸음, 잘하고 있어요.",
  "완벽하지 않아도 괜찮아요. 하나씩 해봐요.",
  "작은 경험도 훌륭한 취업 재료예요.",
  "막막할 땐 지금 할 일 하나만 해봐요.",
  "꾸준함이 결국 취업으로 이어져요.",
  "어제보다 한 걸음 더 나아갔어요.",
  "천천히, 그러나 확실하게 준비돼요."
];

export function pickDailyMessage(dayOfMonth: number): string {
  return dailyMessages[dayOfMonth % dailyMessages.length] ?? dailyMessages[0];
}

// 인사 섹션에 랜덤으로 보여줄 팁 — 이력서·자기소개서·첫 취업·면접·마음가짐.
export function careerTips(t: PlatformT): string[] {
  return [
    t("이력서 경력은 '무엇을'보다 '그래서 어떤 결과'까지 적어야 강해져요.", "On a resume, experience gets stronger when you write not just 'what' but 'what result it led to.'", "简历上的经历，比起『做了什么』，写到『带来了什么结果』才更有力。", "Trong CV, kinh nghiệm mạnh hơn khi bạn ghi không chỉ 'làm gì' mà cả 'kết quả ra sao'.", "履歴書の経歴は『何を』より『それでどんな結果か』まで書くと強くなります。", "Di resume, pengalaman jadi kuat bila menulis bukan hanya 'apa' tapi 'hasilnya apa.'"),
    t("성과에는 숫자를 붙여보세요. '문의 응대'보다 '하루 50건 문의 응대'가 훨씬 와닿아요.", "Attach numbers to achievements. 'Handled 50 inquiries a day' lands far better than 'handled inquiries.'", "给成果加上数字。比起『处理咨询』，『每天处理50件咨询』更打动人。", "Gắn con số vào thành tích. 'Xử lý 50 yêu cầu mỗi ngày' ấn tượng hơn hẳn 'xử lý yêu cầu'.", "成果には数字を添えましょう。『問い合わせ対応』より『1日50件の問い合わせ対応』の方が響きます。", "Sertakan angka pada pencapaian. 'Menangani 50 pertanyaan sehari' jauh lebih mengena daripada 'menangani pertanyaan.'"),
    t("경험이 없다고 생각 말아요. 알바·동아리·과제도 훌륭한 이력서 재료예요.", "Don't think you have no experience. Part-time jobs, clubs, and assignments are great resume material.", "别以为自己没有经验。兼职、社团、作业都是很好的简历素材。", "Đừng nghĩ bạn không có kinh nghiệm. Việc làm thêm, câu lạc bộ, bài tập đều là chất liệu CV tuyệt vời.", "経験がないと思わないで。アルバイト・サークル・課題も立派な履歴書の材料です。", "Jangan merasa tak punya pengalaman. Kerja paruh waktu, klub, dan tugas adalah materi resume yang bagus."),
    t("이력서는 지원 직무에 맞춰 다듬어요. 같은 경험도 강조점이 달라져요.", "Tailor your resume to the role you're applying for. The same experience can be emphasized differently.", "简历要贴合应聘职位来打磨。同样的经验，侧重点也会不同。", "Điều chỉnh CV theo vị trí ứng tuyển. Cùng một kinh nghiệm, điểm nhấn cũng khác đi.", "履歴書は応募職種に合わせて整えます。同じ経験でも強調点が変わります。", "Sesuaikan resume dengan posisi yang dilamar. Pengalaman sama pun bisa ditekankan berbeda."),
    t("자기소개서는 빈 화면부터 채우지 말고, 문항에 하나씩 답하듯 써보세요.", "For your cover letter, don't start from a blank page—write by answering each prompt one by one.", "写自我介绍别从空白页开始，一道题一道题地回答着写吧。", "Với thư xin việc, đừng bắt đầu từ trang trắng—hãy viết bằng cách trả lời từng câu hỏi một.", "自己PRは空白の画面から埋めず、設問に一つずつ答えるように書いてみましょう。", "Untuk surat lamaran, jangan mulai dari halaman kosong—tulis dengan menjawab tiap pertanyaan satu per satu."),
    t("자소서 첫 문장은 결론부터. 읽는 사람은 시간이 많지 않아요.", "Start your cover letter's first sentence with the conclusion. Readers don't have much time.", "自我介绍第一句先说结论。读的人时间不多。", "Câu đầu thư xin việc hãy nêu kết luận trước. Người đọc không có nhiều thời gian.", "自己PRの最初の一文は結論から。読む人は時間が多くありません。", "Kalimat pertama surat lamaran mulai dari kesimpulan. Pembaca tak punya banyak waktu."),
    t("지원 동기엔 '왜 이 회사'가 드러나야 해요. 회사 이름만 바꿔도 되는 글은 피해요.", "Your motivation should show 'why this company.' Avoid text that works just by swapping the company name.", "求职动机要体现『为什么是这家公司』。避免只换公司名就能通用的内容。", "Động cơ ứng tuyển phải thể hiện 'vì sao là công ty này'. Tránh bài chỉ cần đổi tên công ty là dùng được.", "志望動機は『なぜこの会社か』が伝わるように。会社名を変えるだけで通用する文章は避けます。", "Motivasi harus menunjukkan 'mengapa perusahaan ini.' Hindari tulisan yang cukup diganti nama perusahaannya."),
    t("면접 답변은 경험으로 준비해요. 예상 질문에 내 사례를 미리 붙여두면 편해요.", "Prepare interview answers with experiences. Attach your own examples to likely questions in advance.", "用经验准备面试回答。提前把自己的事例贴到预想问题上会更轻松。", "Chuẩn bị câu trả lời phỏng vấn bằng kinh nghiệm. Gắn sẵn ví dụ của bạn vào câu hỏi dự kiến sẽ dễ hơn.", "面接の回答は経験で準備します。想定質問に自分の事例を先に添えておくと楽です。", "Siapkan jawaban wawancara dengan pengalaman. Tempelkan contoh Anda ke pertanyaan yang mungkin muncul."),
    t("면접에서 모르는 건 솔직하게. 대신 '어떻게 배우겠다'를 덧붙이면 좋아요.", "In interviews, be honest about what you don't know. Then add 'how you'd learn it.'", "面试中不懂就坦诚说。再补上『我会怎样去学』就更好。", "Trong phỏng vấn, hãy thành thật về điều mình chưa biết. Rồi thêm 'sẽ học như thế nào'.", "面接で分からないことは正直に。代わりに『どう学ぶか』を添えると良いです。", "Dalam wawancara, jujur soal yang tidak Anda ketahui. Lalu tambahkan 'bagaimana akan mempelajarinya.'"),
    t("첫 직장은 '완벽한 곳'보다 '성장할 수 있는 곳'을 기준으로 봐도 좋아요.", "For your first job, it's fine to choose 'a place to grow' over 'a perfect place.'", "选第一份工作，比起『完美的地方』，以『能成长的地方』为标准也很好。", "Với công việc đầu tiên, chọn 'nơi có thể phát triển' hơn 'nơi hoàn hảo' cũng tốt.", "初めての職場は『完璧な所』より『成長できる所』を基準にしても良いです。", "Untuk pekerjaan pertama, memilih 'tempat untuk berkembang' ketimbang 'tempat sempurna' pun baik."),
    t("이력서 한 장에 다 담으려 하지 말고, 직무와 관련된 것부터 위로 올려요.", "Don't try to cram everything onto one page—put job-relevant items at the top.", "别想把所有内容塞进一页简历，把与职位相关的放在上面。", "Đừng cố nhồi hết vào một trang—đưa những gì liên quan đến vị trí lên trên.", "履歴書1枚に全部詰め込まず、職務に関連するものから上に置きます。", "Jangan coba memuat semua dalam satu halaman—taruh yang relevan dengan posisi di atas."),
    t("약어·전문용어는 풀어서. 읽는 사람이 바로 이해할 수 있어야 해요.", "Spell out abbreviations and jargon. The reader should understand right away.", "缩写和专业术语要展开说明。要让读的人一看就懂。", "Giải thích từ viết tắt và thuật ngữ chuyên môn. Người đọc phải hiểu ngay.", "略語・専門用語はかみ砕いて。読む人がすぐ理解できるように。", "Uraikan singkatan dan istilah teknis. Pembaca harus langsung paham."),
    t("경력 기술은 동사로 시작해요. '기획·운영·개선'처럼 한 일을 분명히.", "Start experience descriptions with verbs. Make what you did clear, like 'planned, ran, improved.'", "经历描述用动词开头。像『策划·运营·改进』一样明确做过的事。", "Bắt đầu mô tả kinh nghiệm bằng động từ. Nêu rõ việc đã làm như 'lên kế hoạch, vận hành, cải thiện'.", "職務の記述は動詞で始めます。『企画・運営・改善』のように行ったことを明確に。", "Mulai deskripsi pengalaman dengan kata kerja. Perjelas yang dilakukan seperti 'merancang, menjalankan, memperbaiki'."),
    t("자기소개서의 '성격의 장단점'은 단점 뒤에 개선 노력을 함께 적어요.", "For 'strengths and weaknesses' in a cover letter, follow the weakness with your effort to improve it.", "自我介绍里的『性格优缺点』，缺点后面要写上改进的努力。", "Với 'ưu và nhược điểm' trong thư xin việc, sau nhược điểm hãy ghi nỗ lực cải thiện.", "自己PRの『性格の長所・短所』は、短所の後に改善の努力も書きます。", "Untuk 'kelebihan dan kekurangan' di surat lamaran, ikuti kekurangan dengan upaya memperbaikinya."),
    t("지원 전, 채용 공고의 '자격요건' 키워드를 이력서에 자연스럽게 녹여보세요.", "Before applying, weave the job posting's 'requirement' keywords naturally into your resume.", "投递前，把招聘启事里『任职要求』的关键词自然地融入简历。", "Trước khi ứng tuyển, hãy đưa từ khóa 'yêu cầu' trong tin tuyển dụng vào CV một cách tự nhiên.", "応募前に、求人の『応募資格』キーワードを履歴書に自然に盛り込みましょう。", "Sebelum melamar, sisipkan kata kunci 'persyaratan' dari lowongan ke resume secara alami."),
    t("면접 복장이 고민되면 그 회사 톤보다 half 정도만 단정하게 맞춰요.", "If unsure what to wear to an interview, dress just a notch neater than the company's style.", "面试穿着犹豫时，比公司的风格再端庄一点点就好。", "Nếu phân vân về trang phục phỏng vấn, hãy ăn mặc chỉnh tề hơn phong cách công ty một chút.", "面接の服装に迷ったら、その会社のトーンより少しだけきちんと整えます。", "Jika ragu soal busana wawancara, berpakaianlah sedikit lebih rapi dari gaya perusahaan."),
    t("포트폴리오는 '결과 이미지'보다 '내 역할과 기여'를 설명하는 게 중요해요.", "In a portfolio, explaining 'your role and contribution' matters more than the 'final images.'", "作品集里，说明『我的角色与贡献』比『成果图片』更重要。", "Trong portfolio, giải thích 'vai trò và đóng góp của bạn' quan trọng hơn 'hình ảnh kết quả'.", "ポートフォリオは『結果の画像』より『自分の役割と貢献』を説明することが大切です。", "Dalam portofolio, menjelaskan 'peran dan kontribusi Anda' lebih penting daripada 'gambar hasil'."),
    t("지원서 오탈자는 생각보다 크게 보여요. 제출 전 소리 내어 한 번 읽어봐요.", "Typos in applications stand out more than you'd think. Read it aloud once before submitting.", "申请材料里的错别字比想象中更显眼。提交前出声读一遍吧。", "Lỗi chính tả trong đơn nổi bật hơn bạn nghĩ. Hãy đọc to một lần trước khi nộp.", "応募書類の誤字脱字は思ったより目立ちます。提出前に一度声に出して読みましょう。", "Salah ketik di lamaran lebih menonjol dari perkiraan. Baca sekali dengan suara sebelum kirim."),
    t("면접 마지막 '질문 있냐'엔 회사·직무에 대한 진짜 궁금증을 하나 준비해요.", "For the closing 'any questions?', prepare one genuine curiosity about the company or role.", "面试最后问『有问题吗』时，准备一个对公司或职位的真实疑问。", "Với câu hỏi cuối 'bạn có câu hỏi gì không?', hãy chuẩn bị một thắc mắc thật về công ty hoặc vị trí.", "面接最後の『質問はありますか』には、会社・職務への本当の疑問を一つ用意します。", "Untuk pertanyaan penutup 'ada pertanyaan?', siapkan satu keingintahuan tulus soal perusahaan atau posisi."),
    t("연봉·복지 질문은 나쁘지 않아요. 다만 지원 동기부터 충분히 보여준 뒤에.", "Asking about salary and benefits is fine—just after you've shown enough motivation first.", "问薪资福利没什么不好，只是要先充分表达求职动机之后。", "Hỏi về lương và phúc lợi không xấu—chỉ là sau khi đã thể hiện đủ động cơ ứng tuyển.", "年収・福利厚生の質問は悪くありません。ただし志望動機を十分に見せた後で。", "Bertanya soal gaji dan tunjangan tidak buruk—asalkan setelah cukup menunjukkan motivasi."),
    t("경험을 적을 땐 STAR(상황·과제·행동·결과) 순서로 정리하면 술술 풀려요.", "When writing experiences, the STAR order (Situation, Task, Action, Result) makes it flow.", "写经验时，按STAR（情境·任务·行动·结果）顺序整理会很顺畅。", "Khi viết kinh nghiệm, sắp theo thứ tự STAR (Tình huống, Nhiệm vụ, Hành động, Kết quả) sẽ trôi chảy.", "経験を書くときはSTAR(状況・課題・行動・結果)の順で整理すると、すらすら書けます。", "Saat menulis pengalaman, urutan STAR (Situasi, Tugas, Aksi, Hasil) membuatnya mengalir."),
    t("'열정·성실' 같은 단어보다, 그걸 보여준 구체적 행동 한 줄이 힘이 세요.", "One concrete action that shows it beats words like 'passion' or 'diligence.'", "比起『热情·踏实』这类词，一行展示它的具体行动更有力。", "Một dòng hành động cụ thể chứng minh điều đó mạnh hơn những từ như 'nhiệt huyết, tận tâm'.", "『情熱・誠実』のような言葉より、それを示した具体的な行動一行の方が強いです。", "Satu baris aksi konkret yang membuktikannya lebih kuat dari kata seperti 'semangat' atau 'tekun'."),
    t("면접 전날은 새 정보를 욱여넣기보다, 준비한 답을 소리 내어 연습해요.", "The day before an interview, rehearse your prepared answers aloud rather than cramming new info.", "面试前一天，与其硬塞新信息，不如把准备好的答案出声练习。", "Hôm trước phỏng vấn, hãy luyện to các câu trả lời đã chuẩn bị thay vì nhồi thông tin mới.", "面接前日は新しい情報を詰め込むより、準備した答えを声に出して練習します。", "Sehari sebelum wawancara, latih jawaban yang sudah disiapkan dengan suara daripada menjejalkan info baru."),
    t("탈락은 '나 전체'의 평가가 아니에요. 이 자리와의 핏이 아니었을 뿐.", "A rejection isn't a verdict on 'all of you.' It just wasn't a fit for this role.", "落选不是对『整个你』的评价，只是与这个岗位不契合而已。", "Bị từ chối không phải đánh giá 'toàn bộ con người bạn'. Chỉ là không hợp với vị trí này thôi.", "不採用は『あなた全体』の評価ではありません。この席との相性でなかっただけ。", "Penolakan bukan penilaian atas 'seluruh diri Anda'. Hanya kurang cocok dengan posisi ini."),
    t("이력서는 한 번 쓰고 끝이 아니에요. 지원할 때마다 조금씩 다듬는 게 정상.", "A resume isn't write-once. Tweaking it a bit for each application is normal.", "简历不是写一次就完事。每次投递都稍作调整才正常。", "CV không phải viết một lần là xong. Chỉnh một chút cho mỗi lần ứng tuyển là bình thường.", "履歴書は一度書いて終わりではありません。応募のたびに少しずつ整えるのが普通です。", "Resume bukan sekali tulis lalu selesai. Menyesuaikannya sedikit tiap melamar itu wajar."),
    t("자기소개서에 거창한 포부보다, 입사 후 '첫 3개월'에 할 일을 그려보면 진솔해요.", "Instead of grand ambitions, sketching what you'd do in your 'first 3 months' reads as sincere.", "自我介绍里比起宏大抱负，描绘入职后『头三个月』要做的事更真诚。", "Thay vì hoài bão lớn lao, phác thảo việc sẽ làm trong '3 tháng đầu' sau khi vào công ty sẽ chân thành hơn.", "自己PRは大げさな抱負より、入社後『最初の3か月』にすることを描くと誠実に映ります。", "Alih-alih ambisi besar, menggambarkan yang akan dilakukan di '3 bulan pertama' terasa tulus."),
    t("면접은 시험이 아니라 대화예요. 서로 맞는지 확인하는 자리라고 생각해요.", "An interview is a conversation, not a test. Think of it as checking mutual fit.", "面试不是考试，是对话。把它当作确认彼此是否合适的场合。", "Phỏng vấn là cuộc trò chuyện, không phải bài thi. Hãy xem đó là nơi kiểm tra sự phù hợp của cả hai.", "面接は試験ではなく対話です。お互いが合うか確認する場だと考えます。", "Wawancara adalah percakapan, bukan ujian. Anggap sebagai ajang memastikan kecocokan kedua pihak."),
    t("경력이 짧을수록 '배우려는 태도'와 '기초 역량'을 분명히 보여줘요.", "The less experience you have, the more clearly show your 'willingness to learn' and 'fundamentals.'", "经历越短，越要清楚展示『学习的态度』和『基础能力』。", "Kinh nghiệm càng ít, càng phải thể hiện rõ 'thái độ ham học' và 'năng lực nền tảng'.", "経歴が浅いほど『学ぶ姿勢』と『基礎力』をはっきり見せます。", "Semakin sedikit pengalaman, semakin jelas tunjukkan 'sikap mau belajar' dan 'kemampuan dasar'."),
    t("지원 회사 3곳만 깊게 조사해도 자기소개서 퀄리티가 확 올라가요.", "Researching even just 3 target companies deeply lifts your cover letter's quality a lot.", "哪怕只深入调研3家目标公司，自我介绍的质量也会大幅提升。", "Chỉ cần nghiên cứu sâu 3 công ty mục tiêu cũng nâng chất lượng thư xin việc lên nhiều.", "応募先3社だけでも深く調べれば、自己PRの質がぐっと上がります。", "Meneliti mendalam bahkan hanya 3 perusahaan target sangat meningkatkan kualitas surat lamaran."),
    t("이력서 사진은 필수는 아니에요. 넣는다면 밝고 단정한 정면 사진으로.", "A resume photo isn't required. If you include one, use a bright, tidy, front-facing shot.", "简历照片不是必须的。如果要放，用明亮端庄的正面照。", "Ảnh trong CV không bắt buộc. Nếu có, hãy dùng ảnh chính diện sáng và gọn gàng.", "履歴書の写真は必須ではありません。入れるなら明るく端正な正面の写真で。", "Foto di resume tidak wajib. Jika disertakan, gunakan foto depan yang cerah dan rapi."),
    t("'참여했다'보다 '맡아서 ~했다'가 좋아요. 내 몫을 분명히 드러내요.", "'I took charge and did ~' beats 'I participated.' Make your own part clear.", "比起『参与了』，『负责并做了~』更好。要明确自己的那份贡献。", "'Tôi phụ trách và đã làm ~' hay hơn 'tôi tham gia'. Hãy nêu rõ phần của bạn.", "『参加した』より『担当して〜した』が良いです。自分の役割を明確に示します。", "'Saya menangani dan melakukan ~' lebih baik dari 'saya ikut serta'. Perjelas bagian Anda."),
    t("면접 답변은 30초~1분. 너무 길면 핵심이 흐려져요.", "Keep interview answers to 30 seconds–1 minute. Too long blurs the point.", "面试回答控制在30秒~1分钟。太长会模糊重点。", "Câu trả lời phỏng vấn nên 30 giây–1 phút. Quá dài sẽ làm mờ trọng tâm.", "面接の回答は30秒〜1分。長すぎると要点がぼやけます。", "Jawaban wawancara sebaiknya 30 detik–1 menit. Terlalu panjang mengaburkan inti."),
    t("긴장되면 천천히 말해도 괜찮아요. 또박또박이 빠름보다 신뢰를 줘요.", "If you're nervous, speaking slowly is fine. Clear beats fast for building trust.", "紧张时慢慢说也没关系。吐字清楚比语速快更让人信赖。", "Nếu hồi hộp, nói chậm cũng không sao. Rõ ràng tạo niềm tin hơn là nói nhanh.", "緊張したらゆっくり話しても大丈夫。はっきり話す方が速さより信頼を与えます。", "Kalau gugup, bicara pelan tak apa. Jelas lebih membangun kepercayaan daripada cepat."),
    t("직무를 아직 못 정했다면, 관심 가는 공고 10개의 공통점을 찾아봐요.", "If you haven't picked a role yet, look for what 10 postings you like have in common.", "还没定职位的话，找找你感兴趣的10个招聘启事的共同点。", "Nếu chưa chọn được vị trí, hãy tìm điểm chung của 10 tin tuyển dụng bạn thích.", "職種をまだ決められないなら、気になる求人10件の共通点を探してみます。", "Kalau belum menentukan posisi, cari kesamaan dari 10 lowongan yang menarik bagi Anda."),
    t("인턴·계약직 경험도 당당히 적어요. 실무를 해봤다는 건 큰 강점이에요.", "Confidently list internship and contract work. Having done real work is a big strength.", "实习、合同工经验也大方写上。有过实操经验是很大的优势。", "Hãy tự tin ghi cả kinh nghiệm thực tập và hợp đồng. Từng làm thực tế là lợi thế lớn.", "インターン・契約社員の経験も堂々と書きます。実務を経験したことは大きな強みです。", "Cantumkan dengan percaya diri pengalaman magang dan kontrak. Pernah bekerja nyata adalah kekuatan besar."),
    t("자기소개서엔 회사의 인재상 키워드를 내 경험으로 '증명'해 보여줘요.", "In your cover letter, 'prove' the company's ideal-candidate keywords with your own experience.", "自我介绍里用自己的经验去『证明』公司的人才标准关键词。", "Trong thư xin việc, hãy 'chứng minh' từ khóa mẫu người lý tưởng của công ty bằng kinh nghiệm của bạn.", "自己PRでは会社の求める人材像のキーワードを、自分の経験で『証明』して見せます。", "Dalam surat lamaran, 'buktikan' kata kunci kandidat ideal perusahaan dengan pengalaman Anda."),
    t("면접 후엔 받은 질문을 메모해둬요. 다음 면접의 최고의 예상 문제예요.", "After an interview, jot down the questions asked. They're the best prep for your next one.", "面试后把被问到的问题记下来。这是下次面试最好的预想题。", "Sau phỏng vấn, ghi lại các câu hỏi đã được hỏi. Đó là đề dự đoán tốt nhất cho lần sau.", "面接後は聞かれた質問をメモしておきます。次の面接の最高の想定問題です。", "Setelah wawancara, catat pertanyaan yang diajukan. Itu bahan prediksi terbaik untuk wawancara berikutnya."),
    t("이력서 파일명은 '이름_직무_이력서'처럼. 받는 사람 입장에서 정리해줘요.", "Name your resume file like 'Name_Role_Resume.' Organize it from the recipient's view.", "简历文件名用『姓名_职位_简历』这样。从接收方角度来整理。", "Đặt tên file CV kiểu 'Tên_Vịtrí_CV'. Sắp xếp theo góc nhìn người nhận.", "履歴書のファイル名は『名前_職種_履歴書』のように。受け取る人の立場で整理します。", "Beri nama file resume seperti 'Nama_Posisi_Resume'. Rapikan dari sudut pandang penerima."),
    t("'많은 것을 배웠다'로 끝내지 말고, 무엇을 배워 어떻게 쓸지까지 적어요.", "Don't end with 'I learned a lot'—write what you learned and how you'll use it.", "别以『学到了很多』结尾，写清学到了什么、将如何运用。", "Đừng kết bằng 'tôi học được nhiều'—hãy ghi học được gì và sẽ dùng thế nào.", "『多くを学んだ』で終わらせず、何を学んでどう活かすかまで書きます。", "Jangan akhiri dengan 'saya belajar banyak'—tulis apa yang dipelajari dan bagaimana memakainya."),
    t("첫 취업은 속도전이 아니에요. 방향이 맞는지부터 천천히 확인해요.", "Landing your first job isn't a race. Slowly check the direction is right first.", "第一次就业不是速度战。先慢慢确认方向对不对。", "Việc làm đầu tiên không phải cuộc đua tốc độ. Hãy từ từ kiểm tra hướng đi có đúng không trước.", "初めての就職はスピード勝負ではありません。まず方向が合っているかゆっくり確認します。", "Pekerjaan pertama bukan adu cepat. Pastikan dulu arahnya benar secara perlahan."),
    t("공고 마감 임박에 몰아 쓰지 말고, 관심 공고는 미리 초안을 잡아둬요.", "Don't rush at the deadline—draft applications for postings you like in advance.", "别等截止临近才赶写，感兴趣的招聘启事提前打好草稿。", "Đừng dồn viết sát hạn—hãy soạn nháp trước cho các tin tuyển dụng bạn quan tâm.", "締切間際に一気に書かず、気になる求人は先に下書きを作っておきます。", "Jangan menumpuk saat mendekati tenggat—buat draf lebih awal untuk lowongan yang diminati."),
    t("면접에서 회사 자랑 대신 '내가 기여할 부분'을 말하면 인상이 달라져요.", "In interviews, talking about 'what you'll contribute' instead of praising the company changes the impression.", "面试中不夸公司，而说『我能贡献的部分』，印象会不一样。", "Trong phỏng vấn, nói về 'phần bạn sẽ đóng góp' thay vì khen công ty sẽ tạo ấn tượng khác.", "面接では会社の称賛の代わりに『自分が貢献できる部分』を話すと印象が変わります。", "Dalam wawancara, membahas 'kontribusi Anda' alih-alih memuji perusahaan mengubah kesan."),
    t("자소서 문항 글자 수는 80~100%를 채우는 게 안정적이에요.", "Filling 80–100% of a cover letter's character limit is a safe bet.", "自我介绍每题字数填到80~100%比较稳妥。", "Viết đầy 80–100% giới hạn ký tự của câu hỏi thư xin việc là an toàn.", "自己PRの設問の文字数は80〜100%埋めるのが無難です。", "Mengisi 80–100% batas karakter pertanyaan surat lamaran itu aman."),
    t("경험이 겹치면 가장 강한 것 하나를 깊게. 얕게 여러 개보다 나아요.", "When experiences overlap, go deep on the strongest one. Better than many shallow ones.", "经验重复时，深入写最强的一个。比多个浅显的更好。", "Khi kinh nghiệm trùng lặp, hãy đào sâu cái mạnh nhất. Tốt hơn nhiều cái hời hợt.", "経験が重なるなら最も強い一つを深く。浅く複数より良いです。", "Jika pengalaman tumpang tindih, dalami yang paling kuat. Lebih baik dari banyak yang dangkal."),
    t("면접 예상 질문 Top3: 자기소개, 지원 동기, 강점. 이건 꼭 준비해요.", "Top 3 likely interview questions: self-intro, motivation, strengths. Always prepare these.", "面试预想题Top3：自我介绍、求职动机、优势。这些一定要准备。", "Top 3 câu hỏi phỏng vấn dự kiến: giới thiệu bản thân, động cơ, điểm mạnh. Nhất định phải chuẩn bị.", "面接の想定質問Top3：自己紹介、志望動機、強み。これは必ず準備します。", "3 pertanyaan wawancara teratas: perkenalan diri, motivasi, kelebihan. Wajib siapkan ini."),
    t("이력서의 '어학·자격'은 최신순·관련순으로. 오래되거나 무관한 건 과감히 빼요.", "List 'languages and certifications' by recency and relevance. Boldly drop old or unrelated ones.", "简历的『语言·资格』按最新、相关排序。过时或无关的果断删掉。", "Liệt kê 'ngoại ngữ và chứng chỉ' theo mới nhất và liên quan. Mạnh dạn bỏ cái cũ hoặc không liên quan.", "履歴書の『語学・資格』は最新順・関連順で。古いものや無関係なものは思い切って外します。", "Susun 'bahasa dan sertifikasi' berdasarkan terbaru dan relevan. Berani hapus yang lama atau tak relevan."),
    t("'커뮤니케이션 능력'은 말로 하지 말고, 갈등을 조율한 사례로 보여줘요.", "Don't claim 'communication skills'—show them with a case where you resolved conflict.", "别嘴上说『沟通能力』，用协调冲突的事例来展示。", "Đừng nói suông 'kỹ năng giao tiếp'—hãy chứng minh bằng ví dụ bạn đã hòa giải xung đột.", "『コミュニケーション能力』は言葉でなく、対立を調整した事例で見せます。", "Jangan sekadar klaim 'kemampuan komunikasi'—tunjukkan lewat contoh menengahi konflik."),
    t("지원 직무의 하루 일과를 상상해보면, 무엇을 강조할지 보이기 시작해요.", "Imagining a day in the target role starts to show you what to emphasize.", "想象一下应聘职位的一天工作，就会开始明白该强调什么。", "Hình dung một ngày làm việc ở vị trí ứng tuyển sẽ dần cho thấy nên nhấn mạnh điều gì.", "応募職種の一日の業務を想像すると、何を強調すべきか見え始めます。", "Membayangkan satu hari di posisi yang dilamar mulai menunjukkan apa yang perlu ditekankan."),
    t("면접 답이 막히면 '잠시 생각해보겠습니다' 한마디로 시간을 벌어도 좋아요.", "If you're stuck in an interview, buying time with 'Let me think for a moment' is fine.", "面试答不上来时，用一句『我稍微想一下』来争取时间也可以。", "Nếu bí câu trả lời khi phỏng vấn, câu 'Cho tôi suy nghĩ một chút' để câu giờ cũng được.", "面接で答えに詰まったら『少し考えてみます』の一言で時間を稼いでも良いです。", "Jika buntu saat wawancara, mengulur waktu dengan 'Beri saya waktu berpikir sejenak' tak masalah."),
    t("떨어져도 피드백을 요청해봐요. 답이 오면 다음을 위한 최고의 힌트예요.", "Even after a rejection, ask for feedback. If it comes, it's the best hint for next time.", "落选也试着请求反馈。若有回复，就是下次最好的提示。", "Dù bị từ chối, hãy thử xin phản hồi. Nếu nhận được, đó là gợi ý tốt nhất cho lần sau.", "落ちてもフィードバックを求めてみます。返事が来れば次への最高のヒントです。", "Meski ditolak, coba minta umpan balik. Jika ada, itu petunjuk terbaik untuk berikutnya."),
    t("이력서는 '나 설명서'가 아니라 '이 직무에 맞는 이유' 모음이에요.", "A resume isn't a 'manual about you'—it's a collection of 'reasons you fit this role.'", "简历不是『我的说明书』，而是『适合这个职位的理由』集合。", "CV không phải 'bản hướng dẫn về bạn'—mà là tập hợp 'lý do bạn hợp với vị trí này'.", "履歴書は『自分の取扱説明書』ではなく『この職務に合う理由』の集まりです。", "Resume bukan 'buku panduan tentang Anda'—melainkan kumpulan 'alasan Anda cocok untuk posisi ini'."),
    t("자기소개서 마지막 문단은 '그래서 입사하면'으로 자연스럽게 이어줘요.", "Let your cover letter's last paragraph flow naturally into 'so once I join.'", "自我介绍最后一段自然地过渡到『所以入职后』。", "Hãy để đoạn cuối thư xin việc chuyển tiếp tự nhiên sang 'vì vậy khi vào công ty'.", "自己PRの最後の段落は『だから入社したら』へ自然につなげます。", "Biarkan paragraf terakhir surat lamaran mengalir alami ke 'jadi begitu bergabung'."),
    t("면접장 도착은 10분 전. 마음을 고르는 시간이 답의 여유를 만들어요.", "Arrive 10 minutes early. Time to settle yourself gives your answers room to breathe.", "提前10分钟到面试地点。整理心情的时间会让回答更从容。", "Đến nơi phỏng vấn trước 10 phút. Thời gian ổn định tâm lý giúp câu trả lời thư thái hơn.", "面接会場には10分前に到着。気持ちを整える時間が答えに余裕を生みます。", "Tiba di lokasi wawancara 10 menit lebih awal. Waktu menenangkan diri memberi kelegaan pada jawaban."),
    t("경험 정리는 오늘 딱 한 개만. 쌓이면 어느새 이력서가 완성돼요.", "Organize just one experience today. As they pile up, your resume quietly gets done.", "今天只整理一个经验。积累起来，简历不知不觉就完成了。", "Hôm nay chỉ sắp xếp đúng một kinh nghiệm. Tích lại thì CV hoàn thành lúc nào không hay.", "経験の整理は今日たった一つだけ。積み重なればいつの間にか履歴書が完成します。", "Rapikan satu pengalaman saja hari ini. Menumpuk lama-lama, resume selesai tanpa terasa."),
    t("'프로젝트 완수'보다 '무엇을 개선했는지'가 기억에 남아요.", "'What you improved' is more memorable than 'completed the project.'", "比起『完成项目』，『改进了什么』更让人记住。", "'Bạn đã cải thiện gì' đáng nhớ hơn 'hoàn thành dự án'.", "『プロジェクト完遂』より『何を改善したか』が記憶に残ります。", "'Apa yang Anda perbaiki' lebih berkesan daripada 'menyelesaikan proyek'."),
    t("지원서마다 회사명 오기입 주의! 복붙 흔적은 성의 없어 보여요.", "Watch for the wrong company name in each application! Copy-paste traces look careless.", "每份申请注意别写错公司名！复制粘贴的痕迹显得没诚意。", "Cẩn thận ghi sai tên công ty ở mỗi đơn! Dấu vết sao chép trông thiếu thành ý.", "応募書類ごとに会社名の誤記に注意！コピペの跡は誠意がなく見えます。", "Waspadai salah tulis nama perusahaan di tiap lamaran! Jejak salin-tempel terlihat tak tulus."),
    t("면접 복기는 잘한 것 1개, 아쉬운 것 1개만. 다음에 딱 그것만 고쳐요.", "Review interviews with just 1 thing done well and 1 to improve. Fix exactly that next time.", "面试复盘只记1个做得好、1个遗憾的。下次就只改那个。", "Rút kinh nghiệm phỏng vấn chỉ 1 điều làm tốt, 1 điều tiếc. Lần sau chỉ sửa đúng điều đó.", "面接の振り返りは良かった点1つ、惜しかった点1つだけ。次はそこだけ直します。", "Tinjau wawancara cukup 1 hal yang baik, 1 yang kurang. Perbaiki tepat itu di lain waktu."),
    t("학점·스펙이 아쉬워도, 그걸 메우는 '경험 스토리'가 있으면 충분해요.", "Even with modest grades and specs, an 'experience story' that fills the gap is enough.", "即使学分、条件不够亮眼，有能弥补的『经验故事』就足够了。", "Dù điểm số và thành tích khiêm tốn, có 'câu chuyện kinh nghiệm' bù lại là đủ.", "成績・スペックが物足りなくても、それを補う『経験のストーリー』があれば十分です。", "Meski nilai dan kualifikasi biasa, punya 'kisah pengalaman' yang menutupinya sudah cukup."),
    t("이력서에 링크(포트폴리오·깃허브)를 넣을 땐 반드시 접속되는지 확인해요.", "When adding links (portfolio, GitHub) to your resume, always check they open.", "简历里放链接（作品集、GitHub）时，一定要确认能打开。", "Khi thêm liên kết (portfolio, GitHub) vào CV, luôn kiểm tra chúng mở được.", "履歴書にリンク(ポートフォリオ・GitHub)を入れるときは必ず接続できるか確認します。", "Saat menambah tautan (portofolio, GitHub) ke resume, selalu pastikan bisa dibuka."),
    t("자소서는 '나'가 아니라 '읽는 사람'이 이해하기 쉬운 글이 좋은 글이에요.", "A good cover letter is easy for 'the reader' to understand, not for 'you.'", "好的自我介绍是让『读的人』而非『自己』容易理解的文字。", "Thư xin việc hay là bài dễ hiểu với 'người đọc', không phải với 'bạn'.", "自己PRは『自分』ではなく『読む人』が理解しやすい文章が良い文章です。", "Surat lamaran yang baik mudah dipahami 'pembaca', bukan 'Anda'."),
    t("면접에서 웃는 얼굴은 실력만큼 강해요. 긴장돼도 입꼬리를 살짝.", "A smile in an interview is as strong as skill. Even when nervous, lift the corners of your mouth a bit.", "面试时的笑容和实力一样有力。紧张也把嘴角微微上扬。", "Nụ cười khi phỏng vấn mạnh như năng lực. Dù hồi hộp, hãy nhếch nhẹ khóe miệng.", "面接での笑顔は実力と同じくらい強いです。緊張しても口角を少し。", "Senyum saat wawancara sekuat kemampuan. Meski gugup, angkat sedikit sudut bibir."),
    t("첫 회사에서 배울 것 하나만 정해두면, 어디를 가도 남는 게 있어요.", "Decide on just one thing to learn at your first company, and you'll gain something wherever you go.", "在第一家公司定下要学的一件事，无论去哪都有收获。", "Chọn sẵn một điều để học ở công ty đầu tiên, đi đâu bạn cũng có thu hoạch.", "最初の会社で学ぶことを一つだけ決めておけば、どこへ行っても残るものがあります。", "Tetapkan satu hal untuk dipelajari di perusahaan pertama, ke mana pun Anda tetap dapat sesuatu."),
    t("'노력했습니다'보다 '이렇게 해서 이만큼 됐습니다'가 설득력 있어요.", "'I did this and got this result' is more convincing than 'I tried hard.'", "比起『我努力了』，『这样做后达到了这个程度』更有说服力。", "'Tôi làm thế này và đạt được thế này' thuyết phục hơn 'tôi đã cố gắng'.", "『努力しました』より『こうしてこれだけになりました』が説得力があります。", "'Saya lakukan ini dan hasilnya sebegini' lebih meyakinkan daripada 'saya berusaha keras'."),
    t("지원 전 회사 최근 소식(뉴스·채용 페이지)을 한 번 훑어보면 답이 달라져요.", "Skimming the company's recent news and careers page before applying changes your answers.", "投递前浏览一下公司近期动态（新闻、招聘页），回答就会不一样。", "Lướt qua tin tức gần đây và trang tuyển dụng của công ty trước khi ứng tuyển sẽ đổi câu trả lời của bạn.", "応募前に会社の最近の情報(ニュース・採用ページ)を一度目を通すと答えが変わります。", "Menyimak berita terbaru dan halaman karier perusahaan sebelum melamar mengubah jawaban Anda."),
    t("면접 예상 질문은 공고 문장에서 나와요. 요구 역량을 질문으로 바꿔 연습해요.", "Likely interview questions come from the posting's wording. Turn required skills into questions and practice.", "面试预想题来自招聘启事的文句。把要求的能力变成问题来练习。", "Câu hỏi phỏng vấn dự kiến đến từ câu chữ trong tin tuyển dụng. Biến năng lực yêu cầu thành câu hỏi để luyện.", "面接の想定質問は求人の文章から出ます。求める力を質問に変えて練習します。", "Pertanyaan wawancara yang mungkin muncul berasal dari teks lowongan. Ubah kompetensi yang diminta jadi pertanyaan lalu latih."),
    t("이력서 여백도 정보예요. 빽빽함보다 읽기 쉬운 배치가 신뢰를 줘요.", "White space on a resume is information too. A readable layout builds more trust than density.", "简历的留白也是信息。比起密密麻麻，易读的排版更让人信赖。", "Khoảng trắng trên CV cũng là thông tin. Bố cục dễ đọc tạo niềm tin hơn là dày đặc.", "履歴書の余白も情報です。ぎっしりより読みやすい配置が信頼を与えます。", "Ruang kosong di resume juga informasi. Tata letak yang mudah dibaca membangun kepercayaan lebih dari kepadatan."),
    t("자기 강점을 모르겠다면, 주변에 '나 하면 떠오르는 거' 세 개를 물어봐요.", "If you don't know your strengths, ask people around you for three things that come to mind about you.", "不清楚自己的优势，就问问身边人『提到我会想到的三个词』。", "Nếu không rõ điểm mạnh của mình, hãy hỏi người xung quanh ba điều họ nghĩ đến về bạn.", "自分の強みが分からないなら、周りに『自分と言えば思い浮かぶこと』を三つ聞いてみます。", "Jika tak tahu kelebihan Anda, tanyakan pada orang sekitar tiga hal yang terlintas tentang Anda."),
    t("면접에서 실수했다고 자책 말아요. 이어지는 답으로 충분히 만회돼요.", "Don't beat yourself up over an interview slip. The answers that follow can more than make up for it.", "别因面试失误而自责。接下来的回答足以弥补。", "Đừng tự trách vì lỡ sai trong phỏng vấn. Các câu trả lời tiếp theo đủ để bù lại.", "面接で失敗したと自分を責めないで。続く答えで十分に挽回できます。", "Jangan menyalahkan diri karena keliru saat wawancara. Jawaban berikutnya cukup untuk menebusnya."),
    t("취업 준비가 지칠 땐, 하루 쉬어도 돼요. 지속이 속도보다 중요해요.", "When job hunting wears you out, taking a day off is okay. Consistency matters more than speed.", "求职累了，休息一天也没关系。坚持比速度更重要。", "Khi mệt vì tìm việc, nghỉ một ngày cũng được. Sự bền bỉ quan trọng hơn tốc độ.", "就活に疲れたら、一日休んでも大丈夫。継続が速さより大切です。", "Saat lelah mencari kerja, libur sehari tak apa. Konsistensi lebih penting daripada kecepatan."),
    t("경력이 없을 땐 '학습 능력'과 '태도'가 최고의 무기예요.", "With no experience, 'learning ability' and 'attitude' are your best weapons.", "没经验时，『学习能力』和『态度』是最好的武器。", "Khi chưa có kinh nghiệm, 'khả năng học hỏi' và 'thái độ' là vũ khí tốt nhất.", "経歴がないときは『学習能力』と『態度』が最高の武器です。", "Tanpa pengalaman, 'kemampuan belajar' dan 'sikap' adalah senjata terbaik."),
    t("이력서 한 줄을 고칠 때마다 조금씩 나아져요. 완성이 아니라 개선이에요.", "Every line you revise makes your resume a little better. It's improvement, not perfection.", "每改一行简历都会好一点。这是改进，不是完成。", "Mỗi dòng bạn sửa làm CV tốt hơn một chút. Đó là cải thiện, không phải hoàn thiện.", "履歴書を一行直すたびに少しずつ良くなります。完成ではなく改善です。", "Setiap baris yang direvisi membuat resume sedikit lebih baik. Ini perbaikan, bukan penyempurnaan."),
    t("면접 답변 끝엔 결론을 한 번 더. '그래서 저는 ~합니다'로 마무리해요.", "End interview answers by restating the conclusion. Wrap up with 'so I ~.'", "面试回答结尾再说一遍结论。用『所以我~』收尾。", "Kết câu trả lời phỏng vấn bằng cách nhắc lại kết luận. Chốt bằng 'vì vậy tôi ~'.", "面接の回答の最後は結論をもう一度。『だから私は〜します』で締めます。", "Akhiri jawaban wawancara dengan menegaskan kembali kesimpulan. Tutup dengan 'jadi saya ~'."),
    t("지원 동기와 입사 후 포부는 하나로 이어지게. 앞뒤가 맞아야 진심이 보여요.", "Connect your motivation and post-hire ambitions as one. Consistency reveals sincerity.", "求职动机和入职后抱负要连成一体。前后一致才显真诚。", "Nối động cơ ứng tuyển và hoài bão sau khi vào làm thành một. Trước sau nhất quán mới thấy sự chân thành.", "志望動機と入社後の抱負は一つにつなげて。前後が合ってこそ本気が見えます。", "Hubungkan motivasi dan ambisi setelah diterima jadi satu. Konsistensi menunjukkan ketulusan."),
    t("자소서에 실패 경험을 쓸 땐, 배움과 변화로 마무리하면 오히려 강점이 돼요.", "When writing about failure in a cover letter, ending with learning and change turns it into a strength.", "自我介绍写失败经历时，以收获和改变收尾，反而会成为优势。", "Khi viết về thất bại trong thư xin việc, kết bằng bài học và thay đổi lại thành điểm mạnh.", "自己PRで失敗経験を書くときは、学びと変化で締めるとむしろ強みになります。", "Saat menulis kegagalan di surat lamaran, mengakhiri dengan pelajaran dan perubahan justru jadi kekuatan."),
    t("면접 대기 중엔 준비한 자기소개를 속으로 한 번 돌려봐요.", "While waiting for your interview, run through your prepared intro once in your head.", "面试等候时，在心里过一遍准备好的自我介绍。", "Trong lúc chờ phỏng vấn, hãy nhẩm lại phần giới thiệu đã chuẩn bị một lần trong đầu.", "面接の待ち時間には、準備した自己紹介を頭の中で一度回してみます。", "Sambil menunggu wawancara, ulangi sekali perkenalan yang sudah disiapkan dalam hati."),
    t("첫 취업의 목표는 '완벽'이 아니라 '시작'이에요. 시작하면 길이 보여요.", "The goal of your first job is 'starting,' not 'perfection.' Once you start, the path appears.", "第一份工作的目标是『开始』而非『完美』。开始了路自然就显现。", "Mục tiêu của việc làm đầu tiên là 'bắt đầu', không phải 'hoàn hảo'. Bắt đầu thì con đường hiện ra.", "初めての就職の目標は『完璧』ではなく『始めること』。始めれば道が見えます。", "Tujuan pekerjaan pertama adalah 'memulai', bukan 'sempurna'. Begitu mulai, jalannya terlihat."),
    t("이력서·자소서는 제출 직전 하루 재워두고 다시 보면 고칠 게 보여요.", "Let your resume and cover letter sit a day before submitting; rereading reveals fixes.", "简历和自我介绍在提交前放一天，再看就能发现要改的地方。", "Để CV và thư xin việc 'ngủ' một ngày trước khi nộp; đọc lại sẽ thấy chỗ cần sửa.", "履歴書・自己PRは提出直前に一日寝かせて見直すと、直すところが見えます。", "Diamkan resume dan surat lamaran sehari sebelum kirim; membacanya ulang menampakkan yang perlu diperbaiki."),
    t("'책임감 있다'는 말 대신, 끝까지 해낸 경험 한 줄로 대신해요.", "Instead of saying 'I'm responsible,' replace it with one line about seeing something through.", "别说『我有责任心』，用一行坚持做到底的经验来代替。", "Thay vì nói 'tôi có trách nhiệm', hãy thay bằng một dòng kinh nghiệm làm đến cùng.", "『責任感がある』という言葉の代わりに、最後までやり遂げた経験一行で示します。", "Alih-alih berkata 'saya bertanggung jawab', ganti dengan satu baris pengalaman menuntaskan sesuatu."),
    t("면접에서 회사에 대한 질문이 없으면 관심이 없어 보여요. 하나는 꼭 준비.", "No questions about the company in an interview looks like a lack of interest. Prepare at least one.", "面试中对公司没有提问会显得没兴趣。一定要准备一个。", "Không có câu hỏi về công ty khi phỏng vấn trông như thiếu quan tâm. Nhất định chuẩn bị một câu.", "面接で会社への質問がないと関心がなく見えます。一つは必ず準備。", "Tanpa pertanyaan soal perusahaan saat wawancara terlihat kurang minat. Siapkan setidaknya satu."),
    t("지원 직무 용어를 이력서에 자연스럽게 쓰면 '이 분야 사람'처럼 보여요.", "Using the target role's terminology naturally in your resume makes you look like 'a person in this field.'", "在简历里自然地使用应聘职位的术语，会显得像『这个领域的人』。", "Dùng thuật ngữ của vị trí ứng tuyển một cách tự nhiên trong CV khiến bạn trông như 'người trong ngành'.", "応募職種の用語を履歴書に自然に使うと『この分野の人』のように見えます。", "Memakai istilah posisi yang dilamar secara alami di resume membuat Anda tampak seperti 'orang di bidang ini'."),
    t("자소서 분량이 안 채워지면, 경험의 '과정'을 한 단계 더 풀어써 봐요.", "If your cover letter runs short, unpack the 'process' of your experience one step further.", "自我介绍字数不够时，把经验的『过程』再展开一层。", "Nếu thư xin việc chưa đủ độ dài, hãy triển khai 'quá trình' của kinh nghiệm thêm một bước.", "自己PRの分量が足りないなら、経験の『過程』をもう一段掘り下げて書いてみます。", "Jika surat lamaran kurang panjang, uraikan 'proses' pengalaman satu langkah lebih dalam."),
    t("면접은 정답 맞히기가 아니라 생각의 과정을 보여주는 자리예요.", "An interview isn't about getting the right answer—it's a place to show how you think.", "面试不是答对题，而是展示思考过程的场合。", "Phỏng vấn không phải đoán đáp án đúng—mà là nơi thể hiện quá trình tư duy.", "面接は正解を当てる場ではなく、考えの過程を見せる場です。", "Wawancara bukan menebak jawaban benar—melainkan tempat menunjukkan cara berpikir Anda."),
    t("탈락 메일에 무너지지 말아요. 합격도 결국 시도 횟수에서 나와요.", "Don't crumble over a rejection email. Offers ultimately come from the number of tries.", "别被拒信击垮。录取最终也来自尝试的次数。", "Đừng gục ngã vì email từ chối. Trúng tuyển rốt cuộc đến từ số lần thử.", "不採用メールに崩れないで。合格も結局は挑戦の回数から生まれます。", "Jangan runtuh karena email penolakan. Tawaran pada akhirnya lahir dari jumlah percobaan."),
    t("이력서 맨 위 3줄이 첫인상이에요. 가장 강한 걸 위로 올려요.", "The top 3 lines of your resume are the first impression. Put the strongest at the top.", "简历最上面3行就是第一印象。把最强的放最上面。", "3 dòng đầu của CV là ấn tượng đầu tiên. Đưa điều mạnh nhất lên trên.", "履歴書の一番上の3行が第一印象です。最も強いものを上に置きます。", "Tiga baris teratas resume adalah kesan pertama. Taruh yang terkuat di atas."),
    t("'다양한 경험'보다 '직무와 연결된 경험'이 더 가치 있어요.", "'Experience tied to the role' is more valuable than 'varied experience.'", "比起『多样的经验』，『与职位相关的经验』更有价值。", "'Kinh nghiệm gắn với vị trí' giá trị hơn 'kinh nghiệm đa dạng'.", "『多様な経験』より『職務につながる経験』の方が価値があります。", "'Pengalaman yang terkait posisi' lebih bernilai daripada 'pengalaman beragam'."),
    t("면접 답을 외우지 말고 키워드만. 외운 티는 대화의 온기를 뺏어요.", "Don't memorize interview answers—just keywords. Sounding rehearsed drains the warmth from the conversation.", "面试答案别背诵，只记关键词。背诵的痕迹会夺走对话的温度。", "Đừng học thuộc câu trả lời phỏng vấn—chỉ từ khóa thôi. Vẻ học thuộc lấy đi sự ấm áp của cuộc trò chuyện.", "面接の答えは暗記せずキーワードだけ。暗記した感じは会話の温かみを奪います。", "Jangan hafalkan jawaban wawancara—cukup kata kunci. Kesan menghafal mengambil kehangatan percakapan."),
    t("지원 회사의 서비스를 직접 써보면, 자소서에 진짜 이야기가 생겨요.", "Actually using the company's product gives your cover letter real stories.", "亲自用一用目标公司的产品，自我介绍里就会有真实的故事。", "Tự mình dùng thử dịch vụ của công ty sẽ tạo nên câu chuyện thật trong thư xin việc.", "応募先のサービスを実際に使ってみると、自己PRに本物の話が生まれます。", "Mencoba langsung produk perusahaan memberi kisah nyata untuk surat lamaran Anda."),
    t("첫 이력서는 3분이면 충분해요. 커리어 노트에 남긴 걸로 시작해봐요.", "Your first resume takes just 3 minutes. Start from what you noted in your career notes.", "第一份简历3分钟就够了。从职业笔记里记下的内容开始吧。", "CV đầu tiên chỉ cần 3 phút. Hãy bắt đầu từ những gì đã ghi trong sổ tay sự nghiệp.", "最初の履歴書は3分で十分です。キャリアノートに残したものから始めてみます。", "Resume pertama cukup 3 menit. Mulailah dari yang Anda catat di catatan karier."),
    t("면접 후 감사 인사(메일·문자)는 짧게. 작은 정성이 오래 남아요.", "Keep a post-interview thank-you (email or text) short. Small courtesies linger.", "面试后的感谢（邮件、短信）要简短。小小的用心会长久留存。", "Lời cảm ơn sau phỏng vấn (email hoặc tin nhắn) nên ngắn gọn. Sự chu đáo nhỏ đọng lại lâu.", "面接後のお礼(メール・メッセージ)は短く。小さな心遣いが長く残ります。", "Ucapan terima kasih setelah wawancara (email atau pesan) singkat saja. Perhatian kecil membekas lama."),
    t("경험을 '나열'하지 말고 '골라' 보여줘요. 편집이 곧 실력이에요.", "Don't 'list' experiences—'curate' them. Editing is a skill in itself.", "别『罗列』经验，要『精选』展示。编辑本身就是能力。", "Đừng 'liệt kê' kinh nghiệm—hãy 'chọn lọc' để trình bày. Biên tập chính là năng lực.", "経験を『羅列』せず『選んで』見せます。編集こそが実力です。", "Jangan 'mendaftar' pengalaman—'kurasi' untuk ditampilkan. Menyunting itu sendiri sebuah keterampilan."),
    t("자소서에 숫자·고유명사가 하나라도 있으면 훨씬 생생해져요.", "Even one number or proper noun in a cover letter makes it far more vivid.", "自我介绍里哪怕有一个数字或专有名词，都会生动很多。", "Chỉ một con số hay danh từ riêng trong thư xin việc cũng khiến nó sống động hơn nhiều.", "自己PRに数字・固有名詞が一つでもあると、ずっと生き生きします。", "Bahkan satu angka atau nama diri dalam surat lamaran membuatnya jauh lebih hidup."),
    t("면접 긴장은 준비량에 반비례해요. 한 번 더 소리 내어 연습해요.", "Interview nerves are inversely proportional to preparation. Practice aloud one more time.", "面试的紧张与准备量成反比。再出声练习一遍。", "Sự hồi hộp khi phỏng vấn tỉ lệ nghịch với mức chuẩn bị. Hãy luyện to thêm một lần.", "面接の緊張は準備量に反比例します。もう一度声に出して練習します。", "Kegugupan wawancara berbanding terbalik dengan persiapan. Latih dengan suara sekali lagi."),
    t("직무가 막막하면, 좋아하는 일보다 '잘하는 일'부터 떠올려봐도 좋아요.", "If the role is unclear, it helps to start from 'what you're good at' rather than what you like.", "对职位迷茫时，先从『擅长的事』而非喜欢的事想起也不错。", "Nếu mơ hồ về vị trí, bắt đầu từ 'việc mình giỏi' thay vì việc mình thích cũng tốt.", "職種に迷ったら、好きなことより『得意なこと』から思い浮かべても良いです。", "Jika bingung soal posisi, mulai dari 'yang Anda kuasai' ketimbang yang disukai juga membantu."),
    t("이력서에 거짓은 절대 금물. 작은 과장도 면접에서 티가 나요.", "Never lie on a resume. Even small exaggerations show in the interview.", "简历上绝对不能撒谎。哪怕小小的夸大，面试时也会露馅。", "Tuyệt đối không nói dối trong CV. Cường điệu nhỏ cũng lộ ra khi phỏng vấn.", "履歴書に嘘は絶対禁物。小さな誇張も面接で分かります。", "Jangan pernah berbohong di resume. Sedikit melebih-lebihkan pun ketahuan saat wawancara."),
    t("자기소개는 '이름+한 줄 강점+지원 직무'면 충분해요. 길지 않아도 돼요.", "A self-intro of 'name + one-line strength + target role' is enough. It needn't be long.", "自我介绍有『姓名+一句优势+应聘职位』就够了，不必很长。", "Giới thiệu bản thân gồm 'tên + một câu điểm mạnh + vị trí ứng tuyển' là đủ. Không cần dài.", "自己紹介は『名前+一言の強み+応募職種』で十分です。長くなくて大丈夫。", "Perkenalan diri berupa 'nama + kelebihan satu baris + posisi yang dilamar' sudah cukup. Tak perlu panjang."),
    t("오늘 할 일 하나만 해봐요. 막막함은 작은 실행 하나로 옅어져요.", "Just do one thing today. One small action thins out the overwhelm.", "今天只做一件事。一个小小的行动就能冲淡茫然。", "Chỉ làm một việc hôm nay. Một hành động nhỏ làm nhạt đi sự mơ hồ.", "今日やることを一つだけやってみます。漠然とした不安は小さな実行一つで薄れます。", "Lakukan satu hal saja hari ini. Satu aksi kecil memudarkan rasa kewalahan.")
  ];
}

export function pickRandomTip(t: PlatformT): string {
  const tips = careerTips(t);
  const i = Math.floor(Math.random() * tips.length);
  return tips[i] ?? tips[0];
}

// 내 커리어 채팅 진입 퍼널 — 홈에서 바로 시작할 수 있는 예시 한 줄.
export const careerChatStarters: { emoji: string; label: string; prompt: string }[] = [
  { emoji: "📜", label: "자격증 땄어요", prompt: "이번에 자격증을 하나 땄어요." },
  { emoji: "🚀", label: "프로젝트 끝냈어요", prompt: "최근에 프로젝트를 하나 마무리했어요." },
  { emoji: "🧩", label: "알바·인턴 했어요", prompt: "알바(또는 인턴)를 하면서 이런 일을 했어요." },
  { emoji: "🏆", label: "공모전·수상", prompt: "공모전에 참가해서 이런 결과가 있었어요." }
];

// 홈 최상단 피처드 배너(광고·이벤트). 추후 실제 배너 데이터로 교체.
export function featuredBanners(t: PlatformT): {
  id: string;
  tag: string;
  title: string;
  subtitle: string;
  href: string;
  from: string;
  to: string;
  image?: string; // 우측 일러스트(있을 때만)
}[] {
  return [
    { id: "b1", tag: t("이벤트", "Event", "活动", "Sự kiện", "イベント", "Acara"), title: t("첫 회원가입하면\nAI 포인트 1000 드려요", "Sign up now\nand get 1,000 AI points", "首次注册\n赠送1000 AI积分", "Đăng ký ngay\nnhận 1.000 điểm AI", "新規登録で\nAIポイント1000プレゼント", "Daftar sekarang\ndapat 1.000 poin AI"), subtitle: t("가입 즉시 지급 · AI 기능에 바로 사용", "Given instantly · use it on AI features right away", "注册即赠 · 立即用于AI功能", "Tặng ngay · dùng cho tính năng AI", "登録後すぐ付与 · AI機能にすぐ利用", "Langsung diberikan · pakai untuk fitur AI"), href: "/talent/settings/points", from: "#0B46E8", to: "#3A6FF0", image: "/images/img_banner_point_signup.webp" },
    { id: "b2", tag: t("사주", "Saju", "四柱", "Tử vi", "四柱", "Saju"), title: t("사주로 보는\n내 직업", "Your job,\nby Saju", "用四柱看\n我的职业", "Nghề của tôi\nqua Tử vi", "四柱で見る\n私の職業", "Pekerjaanku\nlewat Saju"), subtitle: t("생년월일로 알아보는 직업 운", "Career fortune from your birth date", "用生日看职业运", "Vận nghề nghiệp từ ngày sinh", "生年月日で分かる職業運", "Peruntungan karier dari tanggal lahir"), href: "/events/saju", from: "#6D28D9", to: "#9333EA", image: "/img_saju_event_characters.webp" },
    { id: "b3", tag: t("MBTI", "MBTI", "MBTI", "MBTI", "MBTI", "MBTI"), title: t("MBTI로 보는\n내 직업", "Your job,\nby MBTI", "用MBTI看\n我的职业", "Nghề của tôi\nqua MBTI", "MBTIで見る\n私の職業", "Pekerjaanku\nlewat MBTI"), subtitle: t("3분 테스트로 직무 유형 확인", "Find your role type in a 3-min test", "3分钟测出职务类型", "3 phút để biết loại công việc", "3分テストで職務タイプを確認", "Cek tipe kerja dalam tes 3 menit"), href: "/events/mbti", from: "#7A3B12", to: "#C2410C", image: "/images/img_mbti_event_characters.webp" }
  ];
}

// 취업 준비 가이드(편집형 콘텐츠 카드). 카드를 누르면 body 를 팝업으로 보여준다.
export interface CareerGuide {
  emoji: string;
  title: string; // 카드용(줄바꿈 포함)
  desc: string;
  body: { heading: string; text: string }[]; // 팝업 본문
  href?: string; // 관련 도구로 이동(선택)
  ctaLabel?: string;
}

export function careerGuides(t: PlatformT): CareerGuide[] {
  return [
    {
      emoji: "🎯",
      title: t("나에게 맞는\n직무부터 찾기", "Find the\nright role first", "先找到\n适合我的职位", "Tìm vị trí\nphù hợp trước", "自分に合う\n職種から探す", "Temukan dulu\nposisi yang cocok"),
      desc: t("관심 직무를 정하면 공고가 잘 맞아요", "Pick roles you like and postings fit better", "定下感兴趣的职位，招聘信息更契合", "Chọn vị trí quan tâm, tin tuyển dụng sẽ hợp hơn", "興味のある職種を決めると求人がよく合います", "Pilih posisi yang diminati, lowongan lebih cocok"),
      href: "/talent/jobs",
      ctaLabel: t("포지션 탐색하기", "Explore positions", "探索职位", "Khám phá vị trí", "ポジションを探す", "Jelajahi posisi"),
      body: [
        { heading: t("1. 관심 직무를 3개만 골라요", "1. Pick just 3 roles you like", "1. 只选3个感兴趣的职位", "1. Chỉ chọn 3 vị trí quan tâm", "1. 興味のある職種を3つだけ選ぶ", "1. Pilih 3 posisi yang diminati saja"), text: t("너무 넓히지 말고, 지금 끌리는 직무 2~3개만 정해요. 관심 직무를 설정하면 맞는 공고만 모아서 볼 수 있어요.", "Don't spread too wide—settle on just 2–3 roles that appeal to you now. Setting your roles of interest lets you see only the matching postings.", "别铺太广，先定2~3个现在感兴趣的职位。设置感兴趣的职位后，只看匹配的招聘信息。", "Đừng dàn trải quá rộng—chỉ chốt 2–3 vị trí hấp dẫn bạn lúc này. Thiết lập vị trí quan tâm giúp bạn chỉ xem những tin phù hợp.", "広げすぎず、今惹かれる職種を2〜3つだけ決めます。興味のある職種を設定すると合う求人だけまとめて見られます。", "Jangan terlalu meluas—tetapkan 2–3 posisi yang menarik bagi Anda saat ini. Mengatur posisi minat membuat Anda hanya melihat lowongan yang cocok.") },
        { heading: t("2. '하는 일'을 먼저 봐요", "2. Look at 'the work' first", "2. 先看『做什么』", "2. Xem 'công việc' trước", "2. 『する仕事』をまず見る", "2. Lihat 'pekerjaannya' dulu"), text: t("직무명보다 공고의 '주요 업무'를 봐요. 내가 실제로 매일 하게 될 일이 끌리는지가 더 중요해요.", "Look at a posting's 'key responsibilities' over the job title. Whether the work you'd actually do every day appeals to you matters more.", "比起职位名称，先看招聘的『主要工作』。你每天实际要做的事是否吸引你更重要。", "Xem 'nhiệm vụ chính' của tin tuyển dụng hơn là tên chức danh. Việc bạn thực sự làm mỗi ngày có hấp dẫn không mới quan trọng hơn.", "職種名より求人の『主な業務』を見ます。自分が実際に毎日する仕事が惹かれるかがより大切です。", "Perhatikan 'tugas utama' lowongan ketimbang nama jabatan. Apakah pekerjaan harian Anda menarik lebih penting.") },
        { heading: t("3. 필수 자격요건만 체크", "3. Check only the must-have requirements", "3. 只看必备任职要求", "3. Chỉ kiểm tra yêu cầu bắt buộc", "3. 必須の応募資格だけチェック", "3. Cek hanya syarat wajib"), text: t("'우대사항'은 없어도 괜찮아요. '필수'만 어느 정도 맞으면 충분히 도전해볼 만해요.", "'Preferred' items are okay to lack. If you roughly meet the 'must-haves,' it's well worth a shot.", "『加分项』没有也没关系。只要大致符合『必备』就很值得一试。", "Thiếu mục 'ưu tiên' cũng không sao. Nếu đáp ứng tương đối các mục 'bắt buộc' thì rất đáng thử.", "『優遇事項』はなくても大丈夫。『必須』だけある程度合えば十分挑戦する価値があります。", "Tak masalah tanpa item 'nilai plus'. Jika kira-kira memenuhi yang 'wajib', sangat layak dicoba.") },
        { heading: t("4. 관심 회사를 팔로우해요", "4. Follow companies you like", "4. 关注感兴趣的公司", "4. Theo dõi công ty bạn thích", "4. 気になる会社をフォローする", "4. Ikuti perusahaan yang diminati"), text: t("마음에 드는 회사를 관심 등록해두면, 새 포지션이 열릴 때 알림으로 알려드려요.", "Save companies you like, and we'll notify you when a new position opens.", "把喜欢的公司加入关注，新职位开放时我们会通知你。", "Lưu công ty bạn thích, chúng tôi sẽ báo khi có vị trí mới mở.", "気に入った会社を登録しておくと、新しいポジションが開いたときに通知でお知らせします。", "Simpan perusahaan yang Anda suka, kami beri tahu saat ada posisi baru.") }
      ]
    },
    {
      emoji: "🔎",
      title: t("채용 공고,\n제대로 읽는 법", "How to read\njob postings right", "如何正确\n阅读招聘启事", "Cách đọc\ntin tuyển dụng đúng", "求人を\n正しく読む方法", "Cara membaca\nlowongan dengan benar"),
      desc: t("지원 전에 꼭 확인할 것들", "What to check before applying", "投递前必查的事项", "Những điều cần kiểm tra trước khi ứng tuyển", "応募前に必ず確認すること", "Yang wajib dicek sebelum melamar"),
      href: "/talent/jobs",
      ctaLabel: t("공고 살펴보기", "Browse postings", "查看招聘启事", "Xem tin tuyển dụng", "求人を見てみる", "Lihat lowongan"),
      body: [
        { heading: t("1. 주요 업무 = 내 일상", "1. Key duties = your daily life", "1. 主要工作＝你的日常", "1. Nhiệm vụ chính = cuộc sống hằng ngày của bạn", "1. 主な業務＝自分の日常", "1. Tugas utama = keseharian Anda"), text: t("입사하면 매일 하게 될 일이에요. 여기가 안 끌리면 조건이 좋아도 오래 다니기 어려워요.", "This is what you'll do every day once hired. If it doesn't appeal, good conditions won't keep you there long.", "这是入职后每天要做的事。若这里不吸引你，条件再好也难长久。", "Đây là việc bạn làm mỗi ngày sau khi vào. Nếu không hấp dẫn, điều kiện tốt cũng khó gắn bó lâu.", "入社したら毎日する仕事です。ここが惹かれないと条件が良くても長く続けにくいです。", "Inilah yang Anda kerjakan tiap hari setelah diterima. Jika tak menarik, kondisi bagus pun sulit bertahan lama.") },
        { heading: t("2. 필수 vs 우대 구분", "2. Tell must-have from preferred", "2. 区分必备与加分", "2. Phân biệt bắt buộc và ưu tiên", "2. 必須と優遇を区別する", "2. Bedakan wajib dan nilai plus"), text: t("'필수'는 기준선, '우대'는 있으면 좋은 것. 우대가 부족하다고 지원을 포기하지 마세요.", "'Must-have' is the baseline; 'preferred' is nice to have. Don't give up applying just because you lack the preferred items.", "『必备』是底线，『加分』是有更好。别因加分项不足就放弃投递。", "'Bắt buộc' là chuẩn cơ bản, 'ưu tiên' là có thì tốt. Đừng bỏ ứng tuyển chỉ vì thiếu mục ưu tiên.", "『必須』は基準線、『優遇』はあれば良いもの。優遇が足りないからと応募を諦めないでください。", "'Wajib' adalah garis dasar, 'nilai plus' sekadar bonus. Jangan urung melamar hanya karena kurang item nilai plus.") },
        { heading: t("3. 근무 조건 확인", "3. Check working conditions", "3. 确认工作条件", "3. Kiểm tra điều kiện làm việc", "3. 勤務条件を確認する", "3. Cek kondisi kerja"), text: t("근무지·근무 시간·고용 형태(인턴/정규)를 미리 확인해요. 지원 후 후회를 줄여줘요.", "Check location, hours, and employment type (intern/full-time) in advance. It cuts down regret after applying.", "提前确认工作地点、工作时间、雇佣形式（实习/正式）。能减少投递后的后悔。", "Kiểm tra trước địa điểm, giờ làm và loại hình (thực tập/chính thức). Giúp giảm hối tiếc sau khi ứng tuyển.", "勤務地・勤務時間・雇用形態(インターン/正社員)を先に確認します。応募後の後悔を減らします。", "Cek lebih dulu lokasi, jam, dan status kerja (magang/tetap). Mengurangi penyesalan setelah melamar.") },
        { heading: t("4. 마감·전형 절차", "4. Deadline and hiring steps", "4. 截止与招聘流程", "4. Hạn nộp và quy trình tuyển", "4. 締切・選考プロセス", "4. Tenggat dan tahapan seleksi"), text: t("마감일과 전형 단계를 보고 준비 일정을 잡아요. 서류 → 과제 → 면접 흐름을 미리 그려두면 여유로워요.", "Set your prep schedule based on the deadline and hiring stages. Mapping the documents → assignment → interview flow in advance keeps you at ease.", "根据截止日和招聘阶段安排准备日程。提前描绘『材料→作业→面试』的流程会更从容。", "Lên lịch chuẩn bị theo hạn nộp và các vòng tuyển. Phác trước dòng chảy hồ sơ → bài tập → phỏng vấn giúp bạn thong thả.", "締切日と選考段階を見て準備日程を組みます。書類→課題→面接の流れを先に描いておくと余裕が生まれます。", "Susun jadwal persiapan berdasarkan tenggat dan tahap seleksi. Memetakan alur berkas → tugas → wawancara lebih dulu membuat tenang.") }
      ]
    },
    {
      emoji: "🗂️",
      title: t("경험이\n이력서가 되기까지", "Turning experience\ninto a resume", "让经验\n变成简历", "Biến kinh nghiệm\nthành CV", "経験が\n履歴書になるまで", "Mengubah pengalaman\nmenjadi resume"),
      desc: t("알바·프로젝트를 취업 언어로 바꾸는 법", "How to turn part-time jobs and projects into job-search language", "把兼职、项目转化为求职语言的方法", "Cách chuyển việc làm thêm và dự án thành ngôn ngữ xin việc", "アルバイト・プロジェクトを就活の言葉に変える方法", "Cara mengubah kerja paruh waktu dan proyek jadi bahasa lamaran"),
      href: "/talent/career/resume",
      ctaLabel: t("이력서 만들기", "Build a resume", "制作简历", "Tạo CV", "履歴書を作る", "Buat resume"),
      body: [
        { heading: t("1. 경험은 '결과'까지 적어요", "1. Write experiences down to the 'result'", "1. 经验要写到『结果』", "1. Ghi kinh nghiệm đến cả 'kết quả'", "1. 経験は『結果』まで書く", "1. Tulis pengalaman sampai 'hasil'"), text: t("무엇을 했는지에서 멈추지 말고, 그래서 어떤 변화가 생겼는지까지 적어야 이력서 문장이 됩니다. 예: '주문을 받았다' → '주문 누락을 30% 줄였다'.", "Don't stop at what you did—write what changed as a result to make it a resume sentence. e.g., 'took orders' → 'cut order errors by 30%.'", "别只停在做了什么，还要写出因此带来的改变，才能成为简历句子。例：『接单』→『把订单遗漏减少了30%』。", "Đừng dừng ở việc đã làm gì—hãy ghi cả thay đổi nó tạo ra để thành câu trong CV. Ví dụ: 'nhận đơn' → 'giảm 30% đơn bị sót'.", "何をしたかで止めず、それでどんな変化が生まれたかまで書くと履歴書の文になります。例：『注文を受けた』→『注文漏れを30%減らした』。", "Jangan berhenti di apa yang dilakukan—tulis perubahan hasilnya agar jadi kalimat resume. Mis.: 'menerima pesanan' → 'menurunkan kesalahan pesanan 30%'.") },
        { heading: t("2. 숫자로 구체화해요", "2. Make it concrete with numbers", "2. 用数字具体化", "2. Cụ thể hóa bằng con số", "2. 数字で具体化する", "2. Konkretkan dengan angka"), text: t("'많이', '자주' 대신 숫자를 넣어보세요. '하루 50건 응대', '방문자 2배' 처럼 수치가 있으면 훨씬 설득력 있어요.", "Use numbers instead of 'a lot' or 'often.' Figures like 'handled 50 a day' or 'doubled visitors' are far more convincing.", "别用『很多』『经常』，换成数字。像『每天处理50件』『访客翻倍』这样的数值更有说服力。", "Dùng con số thay cho 'nhiều', 'thường xuyên'. Số liệu như 'xử lý 50 lượt/ngày', 'gấp đôi khách' thuyết phục hơn nhiều.", "『多く』『よく』の代わりに数字を入れましょう。『1日50件対応』『訪問者2倍』のように数値があると説得力が増します。", "Gunakan angka alih-alih 'banyak' atau 'sering'. Angka seperti 'menangani 50 per hari', 'pengunjung 2 kali lipat' jauh lebih meyakinkan.") },
        { heading: t("3. 직무에 맞춰 골라요", "3. Curate for the role", "3. 按职位来筛选", "3. Chọn lọc theo vị trí", "3. 職務に合わせて選ぶ", "3. Kurasi sesuai posisi"), text: t("같은 경험도 지원 직무에 따라 강조점이 달라져요. 지원 직무의 자격요건 키워드를 떠올리며 관련된 경험부터 위로 올려요.", "The same experience is emphasized differently by role. Keep the requirement keywords in mind and move related experiences to the top.", "同样的经验会因应聘职位不同而侧重不同。想着应聘职位的任职要求关键词，把相关经验往上放。", "Cùng kinh nghiệm nhưng điểm nhấn khác theo vị trí. Nhớ từ khóa yêu cầu của vị trí và đưa kinh nghiệm liên quan lên trên.", "同じ経験でも応募職種によって強調点が変わります。応募職種の応募資格キーワードを思い浮かべ、関連する経験から上に置きます。", "Pengalaman sama ditekankan berbeda per posisi. Ingat kata kunci persyaratan posisi dan naikkan pengalaman terkait ke atas.") },
        { heading: t("4. 작게 자주 남겨요", "4. Jot small and often", "4. 少量、经常地记录", "4. Ghi ít mà thường xuyên", "4. 小さく頻繁に残す", "4. Catat sedikit tapi sering"), text: t("완벽하게 쓰려 하지 말고, 오늘 있었던 일을 한 줄씩 남겨두면 어느새 이력서 재료가 쌓여요.", "Don't aim for perfect—leave a line about today, and resume material quietly piles up.", "别追求写得完美，把今天发生的事记一行，简历素材不知不觉就攒起来了。", "Đừng cố viết hoàn hảo—ghi một dòng về hôm nay, chất liệu CV sẽ tích lại lúc nào không hay.", "完璧に書こうとせず、今日あったことを一行ずつ残すと、いつの間にか履歴書の材料が溜まります。", "Jangan mengejar sempurna—tinggalkan satu baris tentang hari ini, materi resume menumpuk tanpa terasa.") }
      ]
    },
    {
      emoji: "📝",
      title: t("막막한 자기소개서,\n질문으로 시작", "Daunting cover letter?\nStart with the prompts", "自我介绍无从下笔？\n从问题开始", "Thư xin việc bí ý?\nBắt đầu từ câu hỏi", "手が止まる自己PR、\n設問から始める", "Surat lamaran buntu?\nMulai dari pertanyaan"),
      desc: t("빈 화면 대신 문항에 답하며 채우기", "Fill it by answering prompts instead of facing a blank page", "不面对空白页，而是回答问题来填写", "Điền bằng cách trả lời câu hỏi thay vì đối mặt trang trắng", "空白の画面ではなく設問に答えながら埋める", "Isi dengan menjawab pertanyaan alih-alih menatap halaman kosong"),
      href: "/talent/career/cover",
      ctaLabel: t("자기소개서 시작하기", "Start a cover letter", "开始写自我介绍", "Bắt đầu thư xin việc", "自己PRを始める", "Mulai surat lamaran"),
      body: [
        { heading: t("1. 문항에 답하듯 써요", "1. Write by answering prompts", "1. 像回答问题一样写", "1. Viết như trả lời câu hỏi", "1. 設問に答えるように書く", "1. Tulis seperti menjawab pertanyaan"), text: t("빈 화면을 채우려 하지 말고, '지원 동기', '강점', '입사 후 포부' 같은 문항에 하나씩 답해보세요. 훨씬 수월해져요.", "Rather than filling a blank page, answer prompts like 'motivation,' 'strengths,' and 'ambitions after joining' one by one. It gets much easier.", "别想着填满空白页，逐一回答『求职动机』『优势』『入职后抱负』这类问题吧，会轻松许多。", "Thay vì lấp trang trắng, hãy trả lời từng câu như 'động cơ', 'điểm mạnh', 'hoài bão sau khi vào'. Sẽ dễ hơn nhiều.", "空白の画面を埋めようとせず、『志望動機』『強み』『入社後の抱負』などの設問に一つずつ答えてみましょう。ずっと楽になります。", "Alih-alih mengisi halaman kosong, jawab satu per satu pertanyaan seperti 'motivasi', 'kelebihan', 'ambisi setelah bergabung'. Jauh lebih mudah.") },
        { heading: t("2. 결론부터 말해요", "2. Lead with the conclusion", "2. 先说结论", "2. Nói kết luận trước", "2. 結論から言う", "2. Mulai dari kesimpulan"), text: t("읽는 사람은 시간이 많지 않아요. 첫 문장에 핵심을 두고, 뒤에서 경험으로 뒷받침하는 구성이 좋아요.", "Readers don't have much time. Put the point in the first sentence and back it up with experience afterward.", "读的人时间不多。把重点放在第一句，后面用经验来支撑更好。", "Người đọc không có nhiều thời gian. Đặt trọng tâm ở câu đầu, sau đó dùng kinh nghiệm để chống đỡ.", "読む人は時間が多くありません。最初の一文に核心を置き、後で経験で裏づける構成が良いです。", "Pembaca tak punya banyak waktu. Taruh inti di kalimat pertama, lalu dukung dengan pengalaman.") },
        { heading: t("3. '왜 이 회사'가 보이게", "3. Make 'why this company' clear", "3. 让『为什么是这家公司』显现", "3. Làm rõ 'vì sao công ty này'", "3. 『なぜこの会社か』が見えるように", "3. Perjelas 'mengapa perusahaan ini'"), text: t("회사 이름만 바꿔도 되는 글은 피해요. 그 회사의 서비스를 써보고, 왜 끌렸는지 진짜 이야기를 담아요.", "Avoid text that works by just swapping the company name. Use their product and put in the real story of what drew you.", "避免只换公司名就能通用的内容。用一用他们的产品，写出你被什么吸引的真实故事。", "Tránh bài chỉ cần đổi tên công ty là dùng được. Hãy dùng thử sản phẩm của họ và kể câu chuyện thật về điều thu hút bạn.", "会社名を変えるだけで通用する文章は避けます。その会社のサービスを使ってみて、なぜ惹かれたか本当の話を盛り込みます。", "Hindari tulisan yang cukup diganti nama perusahaannya. Coba produk mereka dan masukkan kisah nyata tentang apa yang menarik Anda.") },
        { heading: t("4. 실패도 강점이 돼요", "4. Failure can be a strength", "4. 失败也能成为优势", "4. Thất bại cũng thành điểm mạnh", "4. 失敗も強みになる", "4. Kegagalan pun jadi kekuatan"), text: t("실패 경험은 배움과 변화로 마무리하면 오히려 진솔한 강점이 됩니다.", "Wrap up a failure with learning and change, and it becomes a sincere strength instead.", "把失败经历以收获和改变收尾，反而会成为真诚的优势。", "Kết thúc trải nghiệm thất bại bằng bài học và thay đổi, nó lại trở thành điểm mạnh chân thành.", "失敗経験は学びと変化で締めくくれば、むしろ誠実な強みになります。", "Akhiri pengalaman gagal dengan pelajaran dan perubahan, justru jadi kekuatan yang tulus.") }
      ]
    },
    {
      emoji: "💬",
      title: t("면접 예상 질문\n미리 준비하기", "Prep likely interview\nquestions in advance", "提前准备\n面试预想题", "Chuẩn bị trước\ncâu hỏi phỏng vấn", "面接の想定質問を\n先に準備する", "Siapkan lebih awal\npertanyaan wawancara"),
      desc: t("내 경험으로 답변을 정리해두면 편해요", "Organizing answers with your experiences makes it easier", "用自己的经验整理好回答会更轻松", "Sắp xếp câu trả lời bằng kinh nghiệm sẽ dễ dàng hơn", "自分の経験で回答を整理しておくと楽です", "Menyusun jawaban dengan pengalaman Anda memudahkan"),
      href: "/talent/career/interviews",
      ctaLabel: t("면접 준비하러 가기", "Go prepare for interviews", "去准备面试", "Đi chuẩn bị phỏng vấn", "面接の準備へ", "Mulai persiapan wawancara"),
      body: [
        { heading: t("1. 단골 질문 3개부터", "1. Start with the 3 regulars", "1. 从3个常见问题开始", "1. Bắt đầu từ 3 câu quen thuộc", "1. 定番質問3つから", "1. Mulai dari 3 pertanyaan langganan"), text: t("자기소개, 지원 동기, 강점 — 이 셋은 거의 항상 나와요. 먼저 내 경험을 예시로 붙여 답을 준비해두세요.", "Self-intro, motivation, strengths—these three almost always come up. Prepare answers by attaching your experiences as examples first.", "自我介绍、求职动机、优势——这三个几乎必问。先用自己的经验作例子准备好回答。", "Giới thiệu bản thân, động cơ, điểm mạnh—ba câu này gần như luôn xuất hiện. Hãy chuẩn bị trước bằng cách gắn kinh nghiệm làm ví dụ.", "自己紹介、志望動機、強み — この3つはほぼ必ず出ます。まず自分の経験を例として添えて答えを準備しておきましょう。", "Perkenalan diri, motivasi, kelebihan—tiga ini hampir selalu muncul. Siapkan dulu jawaban dengan menempelkan pengalaman sebagai contoh.") },
        { heading: t("2. 답은 30초~1분", "2. Keep answers to 30s–1min", "2. 回答30秒~1分钟", "2. Trả lời 30 giây–1 phút", "2. 答えは30秒〜1分", "2. Jawaban 30 detik–1 menit"), text: t("너무 길면 핵심이 흐려져요. 결론 → 근거(경험) → 다시 결론 순서로 짧게 정리해요.", "Too long blurs the point. Keep it short in the order conclusion → evidence (experience) → conclusion again.", "太长会模糊重点。按『结论→依据（经验）→再回到结论』的顺序简短整理。", "Quá dài làm mờ trọng tâm. Sắp gọn theo thứ tự kết luận → dẫn chứng (kinh nghiệm) → lại kết luận.", "長すぎると要点がぼやけます。結論→根拠(経験)→再び結論の順で短くまとめます。", "Terlalu panjang mengaburkan inti. Ringkas dengan urutan kesimpulan → bukti (pengalaman) → kesimpulan lagi.") },
        { heading: t("3. 공고에서 질문을 뽑아요", "3. Pull questions from the posting", "3. 从招聘启事里提炼问题", "3. Rút câu hỏi từ tin tuyển dụng", "3. 求人から質問を引き出す", "3. Tarik pertanyaan dari lowongan"), text: t("채용 공고의 '자격요건/우대사항'을 질문으로 바꿔 연습하면, 실제 면접 질문과 거의 겹쳐요.", "Turn the posting's 'requirements/preferred' into questions and practice—they'll overlap heavily with the real interview questions.", "把招聘的『任职要求/加分项』变成问题来练习，会和实际面试题几乎重合。", "Biến 'yêu cầu/ưu tiên' trong tin tuyển dụng thành câu hỏi để luyện—chúng gần như trùng với câu hỏi phỏng vấn thật.", "求人の『応募資格/優遇事項』を質問に変えて練習すると、実際の面接質問とほぼ重なります。", "Ubah 'persyaratan/nilai plus' lowongan jadi pertanyaan lalu latih—akan sangat mirip dengan pertanyaan wawancara sesungguhnya.") },
        { heading: t("4. 모르면 솔직하게", "4. Be honest when unsure", "4. 不懂就坦诚", "4. Không biết thì thành thật", "4. 分からなければ正直に", "4. Jujur bila tak tahu"), text: t("모르는 건 인정하되 '이렇게 배우겠다'를 덧붙이면 태도로 점수를 얻어요.", "Admit what you don't know, but add 'here's how I'd learn it' to score on attitude.", "承认不懂，但补上『我会这样去学』，能在态度上得分。", "Thừa nhận điều chưa biết, nhưng thêm 'tôi sẽ học thế này' để ghi điểm thái độ.", "分からないことは認めつつ『こう学びます』を添えると態度で点を得ます。", "Akui yang tak Anda ketahui, tapi tambahkan 'begini cara saya mempelajarinya' untuk nilai sikap.") }
      ]
    }
  ];
}
